spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/,classpath:/static/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testbase?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

  thymeleaf:
    mode: HTML5
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
  redis:
    database: 0
    host: localhost
    port: 6379
#    password: 123456
    lettuce:
      pool:
        max-active: 800 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 20 # 连接池中的最大空闲连接 默认 8
        min-idle: 2 # 连接池中的最小空闲连接 默认 0
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
    timeout: 30000  #连接超时时间(毫秒)
  cache:
    type: redis
  security:
    user:
      name: user
      password: user



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.machao.student.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.machao.student.dao: debug
server:
  port: 8877

student:
  password: machao
