package com.machao.student.entity;

public class GradeFinal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.number
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.chines
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String chines;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.math
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String math;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.english
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String english;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.physics
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String physics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.chemistry
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String chemistry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.geography
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String geography;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.politics
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String politics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.history
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String history;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.biography
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String biography;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_final.number
     *
     * @return the value of grade_final.number
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_final.number
     *
     * @param number the value for grade_final.number
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_final.chines
     *
     * @return the value of grade_final.chines
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getChines() {
        return chines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_final.chines
     *
     * @param chines the value for grade_final.chines
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setChines(String chines) {
        this.chines = chines == null ? null : chines.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_final.math
     *
     * @return the value of grade_final.math
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getMath() {
        return math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_final.math
     *
     * @param math the value for grade_final.math
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setMath(String math) {
        this.math = math == null ? null : math.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_final.english
     *
     * @return the value of grade_final.english
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_final.english
     *
     * @param english the value for grade_final.english
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setEnglish(String english) {
        this.english = english == null ? null : english.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_final.physics
     *
     * @return the value of grade_final.physics
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getPhysics() {
        return physics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_final.physics
     *
     * @param physics the value for grade_final.physics
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setPhysics(String physics) {
        this.physics = physics == null ? null : physics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_final.chemistry
     *
     * @return the value of grade_final.chemistry
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getChemistry() {
        return chemistry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_final.chemistry
     *
     * @param chemistry the value for grade_final.chemistry
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setChemistry(String chemistry) {
        this.chemistry = chemistry == null ? null : chemistry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_final.geography
     *
     * @return the value of grade_final.geography
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getGeography() {
        return geography;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_final.geography
     *
     * @param geography the value for grade_final.geography
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setGeography(String geography) {
        this.geography = geography == null ? null : geography.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_final.politics
     *
     * @return the value of grade_final.politics
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getPolitics() {
        return politics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_final.politics
     *
     * @param politics the value for grade_final.politics
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setPolitics(String politics) {
        this.politics = politics == null ? null : politics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_final.history
     *
     * @return the value of grade_final.history
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getHistory() {
        return history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_final.history
     *
     * @param history the value for grade_final.history
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setHistory(String history) {
        this.history = history == null ? null : history.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_final.biography
     *
     * @return the value of grade_final.biography
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getBiography() {
        return biography;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_final.biography
     *
     * @param biography the value for grade_final.biography
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setBiography(String biography) {
        this.biography = biography == null ? null : biography.trim();
    }
}