package com.machao.student.entity;

import lombok.Data;

import javax.persistence.Table;

@Table(name="grade_final")
@Data
public class GradeFinal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.number
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */

    private String numberF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.chines
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String chineseFinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.math
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String mathFinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.english
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String englishFinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.physics
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String physicsFinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.chemistry
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String chemistryFinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.geography
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String geographyFinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.politics
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String politicsFinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.history
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String historyFinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_final.biography
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String biographyFinal;



}