package com.machao.student.entity;

import javax.persistence.Id;
import javax.persistence.Table;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.number
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    @Id
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.name
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.sex
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.grade
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.class
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    private Integer classes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.number
     *
     * @return the value of student_info.number
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.number
     *
     * @param number the value for student_info.number
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.name
     *
     * @return the value of student_info.name
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.name
     *
     * @param name the value for student_info.name
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.sex
     *
     * @return the value of student_info.sex
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.sex
     *
     * @param sex the value for student_info.sex
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.grade
     *
     * @return the value of student_info.grade
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.grade
     *
     * @param grade the value for student_info.grade
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.class
     *
     * @return the value of student_info.classes
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public Integer getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.class
     *
     * @param classes the value for student_info.class
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    public void setClasses(Integer classes) {
        this.classes = classes;
    }
}