package com.machao.student.dao;

import com.machao.student.baseMapper.MyMapper;
import com.machao.student.entity.GradeFinal;
import java.util.List;

public interface GradeFinalMapper extends MyMapper<GradeFinal> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_final
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    int insert(GradeFinal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_final
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    List<GradeFinal> selectAll();
}