package com.machao.student.dao;

import com.machao.student.baseMapper.MyMapper;
import com.machao.student.entity.GradeMid;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface GradeMidMapper extends MyMapper<GradeMid> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_mid
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    int insert(GradeMid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_mid
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    List<GradeMid> selectAll();


}