package com.machao.student.dao;

import com.machao.student.baseMapper.MyMapper;
import com.machao.student.entity.Student;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;

import java.util.List;
import java.util.Map;

public interface StudentMapper extends MyMapper<Student> {

    final String MYSELECTSQL = "select number, name, sex, grade, classes from student_info where number like '%${number}%' and name like '%${name}%' " +
            "and grade like '%${grade}%' and classes like '%${classes}%' ";

    final  String MYSELECTSQL01 = "select number, name, sex, grade, classes from student_info where number like '%${number}%' and name_english like '%${name}%' " +
            "and grade like '%${grade}%' and classes like '%${classes}%' ";
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    int insert(Student record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    List<Student> selectAll();

    List<Student> selectByName(String name);

    //List<Student> select()

    List<Student> selectByClasses(Integer Classes);

    List<Student> selectByGrade(Integer Grade);

    List<Student> selectByGradeAndClasses(Map<String,Integer> keys);

    @Select(MYSELECTSQL)
    @Results(id="studentMap", value = {
            @Result(column = "number", property = "number", id = true ),
            @Result(column = "name", property = "name"),
            @Result(column = "sex", property = "sex"),
            @Result(column = "grade", property = "grade"),
            @Result(column = "classes", property = "classes")
    })
    List<Student> selectByPage( String number, String name, Integer grade, Integer classes );

    @Select(MYSELECTSQL01)
    @ResultMap("studentMap")
    List<Student> selectByPageContainEnglish( String number, String name, Integer grade, Integer classes);

}