package com.machao.student.dao;

import com.machao.student.baseMapper.MyMapper;
import com.machao.student.entity.Student;
import java.util.List;
import java.util.Map;

public interface StudentMapper extends MyMapper<Student> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    int insert(Student record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    List<Student> selectAll();

    List<Student> selectByName(String name);

    //List<Student> select()

    List<Student> selectByClasses(Integer Classes);

    List<Student> selectByGrade(Integer Grade);

    List<Student> selectByGradeAndClasses(Map<String,Integer> keys);
}