package com.machao.student.dao;

import com.machao.student.baseMapper.MyMapper;
import com.machao.student.entity.Student;
import org.apache.ibatis.annotations.*;

import java.util.List;
import java.util.Map;

public interface StudentMapper extends MyMapper<Student> {

    final String MYSELECTSQL = "select number, name, sex, grade, classes from student_info where number like '%${number}%' and name like '%${name}%' " +
            "and grade like '%${grade}%' and classes like '%${classes}%' ";

    final  String MYSELECTSQL01 = "select number, name, sex, grade, classes from student_info where number like '%${number}%' and name_english like '%${name}%' " +
            "and grade like '%${grade}%' and classes like '%${classes}%' ";

    final String MYSELECTSQL02 = "select number, name, sex, grade, classes,'${projects}' from student_info stu" +
            "inner join grade_mid gm on stu.number = gm.number " +
            "where number like '%${number}%' and name_english like '%${name}%' " +
            "and grade like '%${grade}%' and classes like '%${classes}%' ";
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    int insert(Student record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_info
     *
     * @mbggenerated Thu Aug 15 14:48:54 CST 2019
     */
    List<Student> selectAll();

    @Select(MYSELECTSQL)
    @Results(id="studentMap", value = {
            @Result(column = "number", property = "number", id = true ),
            @Result(column = "name", property = "name"),
            @Result(column = "sex", property = "sex"),
            @Result(column = "grade", property = "grade"),
            @Result(column = "classes", property = "classes")
    })
    List<Student> selectByPage( String number, String name, Integer grade, Integer classes );

    @Select(MYSELECTSQL01)
    @ResultMap("studentMap")
    List<Student> selectByPageContainEnglish( String number, String name, Integer grade, Integer classes);

    List<Student> selectByPage01(@Param("number")String number, @Param("name")String name, @Param("grade")Integer grade, @Param("classes")Integer classes, @Param("projects")String projects );

    List<Student> selectByPage01ContainEnglish( String number, String name, Integer grade, Integer classes, String projects);

    List<Student> selectAllAndGrade(Integer grade, Integer classes);
}